{
  "abstract": [
    {
      "type": "text",
      "text": "A convenience method that creates and raises an exception."
    }
  ],
  "documentVersion": 0,
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.documentation/documentation/foundation",
        "doc://com.apple.documentation/documentation/foundation/errors_and_exceptions",
        "doc://com.apple.documentation/documentation/foundation/nsexception"
      ]
    ]
  },
  "identifier": {
    "url": "doc://com.apple.documentation/documentation/foundation/nsexception/1569524-raise",
    "interfaceLanguage": "occ"
  },
  "legacy_identifier": 1569524,
  "kind": "symbol",
  "metadata": {
    "title": "raise:format:",
    "role": "symbol",
    "roleHeading": "Type Method",
    "modules": [
      {
        "name": "Foundation"
      }
    ],
    "platforms": [
      {
        "name": "iOS",
        "introducedAt": "2.0",
        "current": "15.2"
      },
      {
        "name": "iPadOS",
        "introducedAt": "2.0",
        "current": "15.2"
      },
      {
        "name": "macOS",
        "introducedAt": "10.0",
        "current": "12.1"
      },
      {
        "name": "Mac Catalyst",
        "introducedAt": "13.0",
        "current": "15.2"
      },
      {
        "name": "tvOS",
        "introducedAt": "9.0",
        "current": "15.2"
      },
      {
        "name": "watchOS",
        "introducedAt": "2.0",
        "current": "8.3"
      }
    ],
    "externalID": "c:objc(cs)NSException(cm)raise:format:",
    "parent": {
      "title": "NSException"
    },
    "symbolKind": "clm"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 1,
    "patch": 0
  },
  "sections": [],
  "variants": [
    {
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ],
      "paths": [
        "documentation/foundation/nsexception/1569524-raise"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation": {
      "title": "Foundation",
      "identifier": "doc://com.apple.documentation/documentation/foundation",
      "url": "/documentation/foundation",
      "type": "topic",
      "kind": "symbol",
      "role": "collection"
    },
    "doc://com.apple.documentation/documentation/foundation/errors_and_exceptions": {
      "title": "Errors and Exceptions",
      "identifier": "doc://com.apple.documentation/documentation/foundation/errors_and_exceptions",
      "url": "/documentation/foundation/errors_and_exceptions",
      "type": "topic",
      "kind": "article",
      "role": "collectionGroup"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception": {
      "title": "NSException",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception",
      "abstract": [
        {
          "type": "text",
          "text": "An object that represents a special condition that interrupts the normal flow of program execution."
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1409498-raise": {
      "title": "raise:format:arguments:",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1409498-raise",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception/1409498-raise",
      "abstract": [
        {
          "type": "text",
          "text": "Creates and raises an exception with the specified name, reason, and arguments."
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "raise:format:arguments:"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1416135-raise": {
      "title": "raise",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1416135-raise",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception/1416135-raise",
      "abstract": [
        {
          "type": "text",
          "text": "Raises the receiver, causing program flow to jump to the local exception handler."
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "raise"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/nsexceptionname": {
      "title": "NSExceptionName",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexceptionname",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexceptionname"
    },
    "doc://com.apple.documentation/documentation/foundation/nsstring": {
      "title": "NSString",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1569530-exceptionwithname": {
      "title": "exceptionWithName:reason:userInfo:",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1569530-exceptionwithname",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception/1569530-exceptionwithname",
      "abstract": [
        {
          "type": "text",
          "text": "Creates and returns an exception object ."
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "exceptionWithName:reason:userInfo:"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1569524-raise": {
      "title": "raise:format:",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1569524-raise",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception/1569524-raise",
      "abstract": [
        {
          "type": "text",
          "text": "A convenience method that creates and raises an exception."
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "raise:format:"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1414506-initwithname": {
      "title": "initWithName:reason:userInfo:",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1414506-initwithname",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception/1414506-initwithname",
      "abstract": [
        {
          "type": "text",
          "text": "Initializes and returns a newly allocated exception object."
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithName:reason:userInfo:"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "url": "/documentation/technologies",
      "kind": "technologies",
      "title": "Technologies"
    }
  },
  "seeAlsoSections": [
    {
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsexception/1569530-exceptionwithname",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1409498-raise",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1414506-initwithname",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1416135-raise"
      ],
      "title": "Creating and Raising an NSException Object",
      "generated": true
    }
  ],
  "primaryContentSections": [
    {
      "kind": "declarations",
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "keyword",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ")"
            },
            {
              "kind": "identifier",
              "text": "raise:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSExceptionName",
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsexceptionname",
              "text": "NSExceptionName"
            },
            {
              "kind": "text",
              "text": ")"
            },
            {
              "kind": "internalParam",
              "text": "name"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "format:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *"
            },
            {
              "kind": "text",
              "text": ")"
            },
            {
              "kind": "internalParam",
              "text": "format"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "internalParam",
              "text": "..."
            },
            {
              "kind": "text",
              "text": ";"
            }
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "macOS",
            "Mac Catalyst",
            "tvOS",
            "watchOS"
          ]
        }
      ]
    },
    {
      "kind": "parameters",
      "languages": [
        "occ"
      ],
      "parameters": [
        {
          "name": "name",
          "content": [
            {
              "type": "paragraph",
              "inlineContent": [
                {
                  "type": "text",
                  "text": "The name of the exception."
                }
              ]
            }
          ]
        },
        {
          "name": "format,",
          "content": [
            {
              "type": "paragraph",
              "inlineContent": [
                {
                  "type": "text",
                  "text": "A human-readable message string (that is, the exception reason) with conversion specifications for the variable arguments that follow. "
                }
              ]
            }
          ]
        },
        {
          "name": "...",
          "content": [
            {
              "type": "paragraph",
              "inlineContent": [
                {
                  "type": "text",
                  "text": "Variable information to be inserted into the formatted exception reason (in the manner of "
                },
                {
                  "type": "codeVoice",
                  "code": "printf"
                },
                {
                  "type": "text",
                  "text": ")."
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "kind": "content",
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "type": "paragraph",
          "inlineContent": [
            {
              "type": "text",
              "text": "The user-defined information is "
            },
            {
              "type": "codeVoice",
              "code": "nil"
            },
            {
              "type": "text",
              "text": " for the generated exception object."
            }
          ]
        }
      ]
    }
  ],
  "legalNotices": {
    "copyright": "Copyright &copy; 2021 Apple Inc. All rights reserved.",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy"
  }
}