{
  "abstract": [
    {
      "type": "text",
      "text": "Creates and returns an exception object ."
    }
  ],
  "documentVersion": 0,
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.documentation/documentation/foundation",
        "doc://com.apple.documentation/documentation/foundation/errors_and_exceptions",
        "doc://com.apple.documentation/documentation/foundation/nsexception"
      ]
    ]
  },
  "identifier": {
    "url": "doc://com.apple.documentation/documentation/foundation/nsexception/1569530-exceptionwithname",
    "interfaceLanguage": "occ"
  },
  "legacy_identifier": 1569530,
  "kind": "symbol",
  "metadata": {
    "title": "exceptionWithName:reason:userInfo:",
    "role": "symbol",
    "roleHeading": "Type Method",
    "modules": [
      {
        "name": "Foundation"
      }
    ],
    "platforms": [
      {
        "name": "iOS",
        "introducedAt": "2.0",
        "current": "14.3"
      },
      {
        "name": "macOS",
        "introducedAt": "10.0",
        "current": "11.1"
      },
      {
        "name": "Mac Catalyst",
        "introducedAt": "13.0",
        "current": "14.3"
      },
      {
        "name": "tvOS",
        "introducedAt": "9.0",
        "current": "14.3"
      },
      {
        "name": "watchOS",
        "introducedAt": "2.0",
        "current": "7.2"
      }
    ],
    "externalID": "c:objc(cs)NSException(cm)exceptionWithName:reason:userInfo:",
    "symbolKind": "clm"
  },
  "schemaVersion": {
    "major": 1,
    "minor": 0,
    "patch": 0
  },
  "sections": [],
  "variants": [
    {
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ],
      "paths": [
        "documentation/foundation/nsexception/1569530-exceptionwithname"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation": {
      "title": "Foundation",
      "identifier": "doc://com.apple.documentation/documentation/foundation",
      "url": "/documentation/foundation",
      "type": "topic",
      "kind": "symbol",
      "role": "collection"
    },
    "doc://com.apple.documentation/documentation/foundation/errors_and_exceptions": {
      "title": "Errors and Exceptions",
      "identifier": "doc://com.apple.documentation/documentation/foundation/errors_and_exceptions",
      "url": "/documentation/foundation/errors_and_exceptions",
      "type": "topic",
      "kind": "article",
      "role": "collectionGroup"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception": {
      "title": "NSException",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1418149-userinfo": {
      "title": "userInfo",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1418149-userinfo",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception/1418149-userinfo",
      "abstract": [
        {
          "type": "text",
          "text": "A dictionary containing application-specific data pertaining to the receiver."
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1415537-reason": {
      "title": "reason",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1415537-reason",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception/1415537-reason",
      "abstract": [
        {
          "type": "text",
          "text": "A string containing a “human-readable” reason for the receiver."
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1414506-initwithname": {
      "title": "initWithName:reason:userInfo:",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1414506-initwithname",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception/1414506-initwithname",
      "abstract": [
        {
          "type": "text",
          "text": "Initializes and returns a newly allocated exception object."
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithName:reason:userInfo:"
        }
      ]
    },
    "devLink-1695208": {
      "identifier": "devLink-1695208",
      "type": "link",
      "title": "Exception Programming Topics",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Exceptions/Exceptions.html#//apple_ref/doc/uid/10000012i"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1410925-name": {
      "title": "name",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1410925-name",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception/1410925-name",
      "abstract": [
        {
          "type": "text",
          "text": "A string used to uniquely identify the receiver."
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/nsexceptionname": {
      "title": "NSExceptionName",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexceptionname",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexceptionname"
    },
    "doc://com.apple.documentation/documentation/foundation/nsstring": {
      "title": "NSString",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.apple.documentation/documentation/foundation/nsdictionary": {
      "title": "NSDictionary",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsdictionary",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsdictionary"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1569530-exceptionwithname": {
      "title": "exceptionWithName:reason:userInfo:",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1569530-exceptionwithname",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception/1569530-exceptionwithname",
      "abstract": [
        {
          "type": "text",
          "text": "Creates and returns an exception object ."
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "exceptionWithName:reason:userInfo:"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1569524-raise": {
      "title": "raise:format:",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1569524-raise",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception/1569524-raise",
      "abstract": [
        {
          "type": "text",
          "text": "A convenience method that creates and raises an exception."
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "raise:format:"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1409498-raise": {
      "title": "raise:format:arguments:",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1409498-raise",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception/1409498-raise",
      "abstract": [
        {
          "type": "text",
          "text": "Creates and raises an exception with the specified name, reason, and arguments."
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "raise:format:arguments:"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1416135-raise": {
      "title": "raise",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1416135-raise",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception/1416135-raise",
      "abstract": [
        {
          "type": "text",
          "text": "Raises the receiver, causing program flow to jump to the local exception handler."
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "raise"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "url": "/documentation/technologies",
      "kind": "technologies",
      "title": "Technologies"
    }
  },
  "seeAlsoSections": [
    {
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsexception/1569524-raise",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1409498-raise",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1414506-initwithname",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1416135-raise"
      ],
      "title": "Creating and Raising an NSException Object",
      "generated": true
    },
    {
      "title": "Related Documentation",
      "generated": false,
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsexception/1418149-userinfo",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1415537-reason",
        "devLink-1695208",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1410925-name"
      ]
    }
  ],
  "primaryContentSections": [
    {
      "kind": "declarations",
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "tokens": [
            {
              "kind": "text",
              "text": "+ ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSException",
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
              "text": "NSException"
            },
            {
              "kind": "text",
              "text": " *"
            },
            {
              "kind": "text",
              "text": ")"
            },
            {
              "kind": "identifier",
              "text": "exceptionWithName:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSExceptionName",
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsexceptionname",
              "text": "NSExceptionName"
            },
            {
              "kind": "text",
              "text": ")"
            },
            {
              "kind": "internalParam",
              "text": "name"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "reason:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " *"
            },
            {
              "kind": "text",
              "text": ")"
            },
            {
              "kind": "internalParam",
              "text": "reason"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "userInfo:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSDictionary",
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsdictionary",
              "text": "NSDictionary"
            },
            {
              "kind": "text",
              "text": " *"
            },
            {
              "kind": "text",
              "text": ")"
            },
            {
              "kind": "internalParam",
              "text": "userInfo"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ],
          "platforms": [
            "iOS",
            "macOS",
            "Mac Catalyst",
            "tvOS",
            "watchOS"
          ]
        }
      ]
    },
    {
      "kind": "parameters",
      "languages": [
        "occ"
      ],
      "parameters": [
        {
          "name": "name",
          "content": [
            {
              "type": "paragraph",
              "inlineContent": [
                {
                  "type": "text",
                  "text": "The name of the exception."
                }
              ]
            }
          ]
        },
        {
          "name": "reason",
          "content": [
            {
              "type": "paragraph",
              "inlineContent": [
                {
                  "type": "text",
                  "text": "A human-readable message string summarizing the reason for the exception."
                }
              ]
            }
          ]
        },
        {
          "name": "userInfo",
          "content": [
            {
              "type": "paragraph",
              "inlineContent": [
                {
                  "type": "text",
                  "text": "A dictionary containing user-defined information relating to the exception"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "kind": "content",
      "content": [
        {
          "anchor": "return_value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "type": "paragraph",
          "inlineContent": [
            {
              "type": "text",
              "text": "The created "
            },
            {
              "type": "codeVoice",
              "code": "NSException"
            },
            {
              "type": "text",
              "text": " object or "
            },
            {
              "type": "codeVoice",
              "code": "nil"
            },
            {
              "type": "text",
              "text": " if the object couldn't be created."
            }
          ]
        }
      ]
    }
  ],
  "legalNotices": {
    "copyright": "Copyright &copy; 2020 Apple Inc. All rights reserved.",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy"
  }
}