{
  "abstract": [
    {
      "type": "text",
      "text": "An object that represents a special condition that interrupts the normal flow of program execution."
    }
  ],
  "documentVersion": 0,
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.documentation/documentation/foundation",
        "doc://com.apple.documentation/documentation/foundation/errors_and_exceptions"
      ]
    ]
  },
  "identifier": {
    "url": "doc://com.apple.documentation/documentation/foundation/nsexception",
    "interfaceLanguage": "occ"
  },
  "legacy_identifier": 1416196,
  "kind": "symbol",
  "metadata": {
    "title": "NSException",
    "role": "symbol",
    "roleHeading": "Class",
    "modules": [
      {
        "name": "Foundation"
      }
    ],
    "platforms": [
      {
        "name": "iOS",
        "introducedAt": "2.0",
        "current": "14.3"
      },
      {
        "name": "macOS",
        "introducedAt": "10.0",
        "current": "11.1"
      },
      {
        "name": "Mac Catalyst",
        "introducedAt": "13.0",
        "current": "14.3"
      },
      {
        "name": "tvOS",
        "introducedAt": "9.0",
        "current": "14.3"
      },
      {
        "name": "watchOS",
        "introducedAt": "2.0",
        "current": "7.2"
      }
    ],
    "externalID": "c:objc(cs)NSException",
    "symbolKind": "cl"
  },
  "schemaVersion": {
    "major": 1,
    "minor": 0,
    "patch": 0
  },
  "sections": [],
  "variants": [
    {
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ],
      "paths": [
        "documentation/foundation/nsexception"
      ]
    },
    {
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ],
      "paths": [
        "documentation/foundation/nsexception"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation": {
      "title": "Foundation",
      "identifier": "doc://com.apple.documentation/documentation/foundation",
      "url": "/documentation/foundation",
      "type": "topic",
      "kind": "symbol",
      "role": "collection"
    },
    "doc://com.apple.documentation/documentation/foundation/errors_and_exceptions": {
      "title": "Errors and Exceptions",
      "identifier": "doc://com.apple.documentation/documentation/foundation/errors_and_exceptions",
      "url": "/documentation/foundation/errors_and_exceptions",
      "type": "topic",
      "kind": "article",
      "role": "collectionGroup"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception": {
      "title": "NSException",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception",
      "abstract": [
        {
          "type": "text",
          "text": "An object that represents a special condition that interrupts the normal flow of program execution."
        }
      ]
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject": {
      "title": "NSObject",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.apple.documentation/documentation/foundation/nssecurecoding": {
      "title": "NSSecureCoding",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nssecurecoding",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.apple.documentation/documentation/foundation/nscopying": {
      "title": "NSCopying",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nscopying",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1569530-exceptionwithname": {
      "title": "exceptionWithName:reason:userInfo:",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1569530-exceptionwithname",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception/1569530-exceptionwithname",
      "abstract": [
        {
          "type": "text",
          "text": "Creates and returns an exception object ."
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "exceptionWithName:reason:userInfo:"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1569524-raise": {
      "title": "raise:format:",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1569524-raise",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception/1569524-raise",
      "abstract": [
        {
          "type": "text",
          "text": "A convenience method that creates and raises an exception."
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "raise:format:"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1409498-raise": {
      "title": "raise:format:arguments:",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1409498-raise",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception/1409498-raise",
      "abstract": [
        {
          "type": "text",
          "text": "Creates and raises an exception with the specified name, reason, and arguments."
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "raise:format:arguments:"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1414506-initwithname": {
      "title": "initWithName:reason:userInfo:",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1414506-initwithname",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception/1414506-initwithname",
      "abstract": [
        {
          "type": "text",
          "text": "Initializes and returns a newly allocated exception object."
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithName:reason:userInfo:"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1416135-raise": {
      "title": "raise",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1416135-raise",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception/1416135-raise",
      "abstract": [
        {
          "type": "text",
          "text": "Raises the receiver, causing program flow to jump to the local exception handler."
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "raise"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1410925-name": {
      "title": "name",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1410925-name",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception/1410925-name",
      "abstract": [
        {
          "type": "text",
          "text": "A string used to uniquely identify the receiver."
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1415537-reason": {
      "title": "reason",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1415537-reason",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception/1415537-reason",
      "abstract": [
        {
          "type": "text",
          "text": "A string containing a “human-readable” reason for the receiver."
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1418149-userinfo": {
      "title": "userInfo",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1418149-userinfo",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception/1418149-userinfo",
      "abstract": [
        {
          "type": "text",
          "text": "A dictionary containing application-specific data pertaining to the receiver."
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1412165-callstackreturnaddresses": {
      "title": "callStackReturnAddresses",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1412165-callstackreturnaddresses",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception/1412165-callstackreturnaddresses",
      "abstract": [
        {
          "type": "text",
          "text": "The call return addresses related to a raised exception."
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/nsexception/1416845-callstacksymbols": {
      "title": "callStackSymbols",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception/1416845-callstacksymbols",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexception/1416845-callstacksymbols",
      "abstract": [
        {
          "type": "text",
          "text": "An array containing the current call stack symbols."
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/nsuncaughtexceptionhandler": {
      "title": "NSUncaughtExceptionHandler",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsuncaughtexceptionhandler",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsuncaughtexceptionhandler"
    },
    "doc://com.apple.documentation/documentation/foundation/nsexceptionname": {
      "title": "NSExceptionName",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsexceptionname",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/nsexceptionname"
    },
    "doc://com.apple.documentation/documentation/foundation/1416853-nsgetuncaughtexceptionhandler": {
      "title": "NSGetUncaughtExceptionHandler",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/1416853-nsgetuncaughtexceptionhandler",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/1416853-nsgetuncaughtexceptionhandler",
      "abstract": [
        {
          "type": "text",
          "text": "Returns the top-level error handler."
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler": {
      "title": "NSSetUncaughtExceptionHandler",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/1409609-nssetuncaughtexceptionhandler",
      "abstract": [
        {
          "type": "text",
          "text": "Changes the top-level error handler."
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/ns_during": {
      "title": "NS_DURING",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/ns_during",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/ns_during",
      "abstract": [
        {
          "type": "text",
          "text": "Marks the start of the exception-handling domain."
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/ns_endhandler": {
      "title": "NS_ENDHANDLER",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/ns_endhandler",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/ns_endhandler",
      "abstract": [
        {
          "type": "text",
          "text": "Marks the end of the local event handler."
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/ns_handler": {
      "title": "NS_HANDLER",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/ns_handler",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/ns_handler",
      "abstract": [
        {
          "type": "text",
          "text": "Marks the end of the exception-handling domain and the start of the local exception handler."
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/ns_valuereturn": {
      "title": "NS_VALUERETURN",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/ns_valuereturn",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/ns_valuereturn",
      "abstract": [
        {
          "type": "text",
          "text": "Permits program control to exit from an exception-handling domain with a value of a specified type."
        }
      ]
    },
    "doc://com.apple.documentation/documentation/foundation/ns_voidreturn": {
      "title": "NS_VOIDRETURN",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/foundation/ns_voidreturn",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/foundation/ns_voidreturn",
      "abstract": [
        {
          "type": "text",
          "text": "Permits program control to exit from an exception-handling domain."
        }
      ]
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "url": "/documentation/technologies",
      "kind": "technologies",
      "title": "Technologies"
    }
  },
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "12.0",
        "12.3 Release Candidate"
      ]
    }
  },
  "relationshipsSections": [
    {
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom",
      "identifiers": [
        "doc://com.apple.documentation/documentation/objectivec/nsobject"
      ]
    },
    {
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nscopying",
        "doc://com.apple.documentation/documentation/foundation/nssecurecoding"
      ]
    }
  ],
  "topicSections": [
    {
      "kind": "taskGroup",
      "title": "Creating and Raising an NSException Object",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsexception/1569530-exceptionwithname",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1569524-raise",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1409498-raise",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1414506-initwithname",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1416135-raise"
      ]
    },
    {
      "kind": "taskGroup",
      "title": "Querying an NSException Object",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsexception/1410925-name",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1415537-reason",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1418149-userinfo"
      ]
    },
    {
      "kind": "taskGroup",
      "title": "Getting Exception Stack Frames",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsexception/1412165-callstackreturnaddresses",
        "doc://com.apple.documentation/documentation/foundation/nsexception/1416845-callstacksymbols"
      ]
    },
    {
      "kind": "taskGroup",
      "title": "Related Types",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsuncaughtexceptionhandler",
        "doc://com.apple.documentation/documentation/foundation/nsexceptionname"
      ]
    },
    {
      "kind": "taskGroup",
      "title": "Functions",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/1416853-nsgetuncaughtexceptionhandler",
        "doc://com.apple.documentation/documentation/foundation/1409609-nssetuncaughtexceptionhandler"
      ]
    },
    {
      "kind": "taskGroup",
      "title": "Legacy Macros",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/ns_during",
        "doc://com.apple.documentation/documentation/foundation/ns_endhandler",
        "doc://com.apple.documentation/documentation/foundation/ns_handler",
        "doc://com.apple.documentation/documentation/foundation/ns_valuereturn",
        "doc://com.apple.documentation/documentation/foundation/ns_voidreturn"
      ]
    }
  ],
  "primaryContentSections": [
    {
      "kind": "declarations",
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSException"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject",
              "text": "NSObject"
            }
          ],
          "platforms": [
            "iOS",
            "macOS",
            "Mac Catalyst",
            "tvOS",
            "watchOS"
          ]
        }
      ]
    },
    {
      "kind": "content",
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "type": "paragraph",
          "inlineContent": [
            {
              "type": "text",
              "text": "Use "
            },
            {
              "type": "reference",
              "isActive": false,
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsexception"
            },
            {
              "type": "text",
              "text": " to implement exception handling. An exception is a special condition that interrupts the normal flow of program execution. Each application can interrupt the program for different reasons. For example, one application might interpret saving a file in a directory that is write-protected as an exception. In this sense, the exception is equivalent to an error. Another application might interpret the user’s key-press (for example, Control-C) as an exception: an indication that a long-running process should abort."
            }
          ]
        }
      ]
    }
  ],
  "legalNotices": {
    "copyright": "Copyright &copy; 2020 Apple Inc. All rights reserved.",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy"
  }
}