{
  "abstract": [
    {
      "type": "text",
      "text": "A reason indicating that no call record matches the intent’s parameter."
    }
  ],
  "documentVersion": 0,
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.documentation/documentation/sirikit",
        "doc://com.apple.documentation/documentation/sirikit/voip_calling",
        "doc://com.apple.documentation/documentation/sirikit/instartcallcallrecordtocallbackunsupportedreason"
      ]
    ]
  },
  "identifier": {
    "url": "doc://com.apple.documentation/documentation/sirikit/instartcallcallrecordtocallbackunsupportedreason/instartcallcallrecordtocallbackunsupportedreasonnomatchingcall",
    "interfaceLanguage": "occ"
  },
  "legacy_identifier": 3649674,
  "kind": "symbol",
  "metadata": {
    "title": "INStartCallCallRecordToCallBackUnsupportedReasonNoMatchingCall",
    "role": "symbol",
    "roleHeading": "Enumeration Case",
    "modules": [
      {
        "name": "Intents"
      }
    ],
    "platforms": [
      {
        "name": "iOS",
        "introducedAt": "14.0",
        "current": "15.2"
      },
      {
        "name": "iPadOS",
        "introducedAt": "14.0",
        "current": "15.2"
      },
      {
        "name": "Mac Catalyst",
        "introducedAt": "14.0",
        "current": "15.2"
      },
      {
        "name": "watchOS",
        "introducedAt": "7.0",
        "current": "8.3"
      }
    ],
    "externalID": "c:@E@INStartCallCallRecordToCallBackUnsupportedReason@INStartCallCallRecordToCallBackUnsupportedReasonNoMatchingCall",
    "parent": {
      "title": "INStartCallCallRecordToCallBackUnsupportedReason"
    },
    "symbolKind": "econst"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 1,
    "patch": 0
  },
  "sections": [],
  "variants": [
    {
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ],
      "paths": [
        "documentation/sirikit/instartcallcallrecordtocallbackunsupportedreason/instartcallcallrecordtocallbackunsupportedreasonnomatchingcall"
      ]
    },
    {
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ],
      "paths": [
        "documentation/sirikit/instartcallcallrecordtocallbackunsupportedreason/nomatchingcall"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/sirikit": {
      "title": "SiriKit",
      "identifier": "doc://com.apple.documentation/documentation/sirikit",
      "url": "/documentation/sirikit",
      "type": "topic",
      "kind": "symbol",
      "role": "collection"
    },
    "doc://com.apple.documentation/documentation/sirikit/voip_calling": {
      "title": "VoIP Calling",
      "identifier": "doc://com.apple.documentation/documentation/sirikit/voip_calling",
      "url": "/documentation/sirikit/voip_calling",
      "type": "topic",
      "kind": "article",
      "role": "collectionGroup"
    },
    "doc://com.apple.documentation/documentation/sirikit/instartcallcallrecordtocallbackunsupportedreason": {
      "title": "INStartCallCallRecordToCallBackUnsupportedReason",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/sirikit/instartcallcallrecordtocallbackunsupportedreason",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/sirikit/instartcallcallrecordtocallbackunsupportedreason",
      "abstract": [
        {
          "type": "text",
          "text": "A reason why your app can’t use a record to call a person back."
        }
      ]
    },
    "doc://com.apple.documentation/documentation/sirikit/instartcallcallrecordtocallbackunsupportedreason/instartcallcallrecordtocallbackunsupportedreasonnomatchingcall": {
      "title": "INStartCallCallRecordToCallBackUnsupportedReasonNoMatchingCall",
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/sirikit/instartcallcallrecordtocallbackunsupportedreason/instartcallcallrecordtocallbackunsupportedreasonnomatchingcall",
      "kind": "symbol",
      "role": "symbol",
      "url": "/documentation/sirikit/instartcallcallrecordtocallbackunsupportedreason/instartcallcallrecordtocallbackunsupportedreasonnomatchingcall",
      "abstract": [
        {
          "type": "text",
          "text": "A reason indicating that no call record matches the intent’s parameter."
        }
      ]
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "type": "topic",
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "url": "/documentation/technologies",
      "kind": "technologies",
      "title": "Technologies"
    }
  },
  "primaryContentSections": [
    {
      "kind": "declarations",
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "tokens": [
            {
              "kind": "identifier",
              "text": "INStartCallCallRecordToCallBackUnsupportedReasonNoMatchingCall"
            },
            {
              "kind": "text",
              "text": " = 1"
            }
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "watchOS"
          ]
        }
      ]
    }
  ],
  "legalNotices": {
    "copyright": "Copyright &copy; 2021 Apple Inc. All rights reserved.",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy"
  }
}